# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300, verbose_name='学员id')),
                ('name', models.CharField(max_length=300, verbose_name='学员姓名')),
                ('product', models.CharField(max_length=300, verbose_name='书目/课')),
                ('ztype', models.CharField(max_length=300, verbose_name='类别')),
                ('bookname', models.CharField(blank=True, max_length=300, null=True, verbose_name='书名')),
                ('expressnum', models.CharField(blank=True, max_length=300, null=True, verbose_name='单号')),
                ('exdate', models.CharField(max_length=300, verbose_name='发书/开课时间')),
                ('webdate', models.CharField(max_length=300, verbose_name='开课时间')),
                ('devf1', models.CharField(blank=True, max_length=300, null=True)),
                ('devf2', models.CharField(blank=True, max_length=300, null=True)),
                ('devf3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hrmresource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zyear', models.CharField(max_length=300, verbose_name='报考年份')),
                ('zdate', models.CharField(max_length=300, verbose_name='报名时间')),
                ('schoolname', models.CharField(max_length=300, verbose_name='校名称')),
                ('zcity', models.CharField(max_length=300, verbose_name='市')),
                ('uname', models.CharField(max_length=300, verbose_name='学员姓名')),
                ('tel', models.CharField(blank=True, max_length=300, null=True, verbose_name='学员手机')),
                ('uaddress', models.CharField(blank=True, max_length=300, null=True, verbose_name='学员地址')),
                ('zpostcode', models.CharField(blank=True, max_length=300, null=True, verbose_name='邮编')),
                ('ubank', models.CharField(blank=True, max_length=300, null=True, verbose_name='银行')),
                ('uid', models.CharField(max_length=300, verbose_name='身份证号')),
                ('uqq', models.CharField(blank=True, max_length=300, null=True, verbose_name='QQ邮箱')),
                ('uaccount', models.CharField(blank=True, max_length=300, null=True, verbose_name='账号')),
                ('upws', models.CharField(blank=True, max_length=300, null=True, verbose_name='密码')),
                ('uwechat', models.CharField(blank=True, max_length=300, null=True, verbose_name='微信号')),
                ('denum', models.CharField(blank=True, max_length=300, null=True, verbose_name='行政代码')),
                ('idcopy', models.CharField(blank=True, max_length=300, null=True, verbose_name='身份证复印件（有、无）')),
                ('ptype', models.CharField(blank=True, max_length=300, null=True, verbose_name='手机型号')),
                ('birth', models.CharField(blank=True, max_length=300, null=True, verbose_name='生日')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300, verbose_name='书目/课')),
                ('devf1', models.CharField(blank=True, max_length=300, null=True)),
                ('devf2', models.CharField(blank=True, max_length=300, null=True)),
                ('devf3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300, verbose_name='学员id')),
                ('uname', models.CharField(max_length=300, verbose_name='学员姓名')),
                ('product', models.CharField(max_length=300, verbose_name='书目/课')),
                ('ztype', models.CharField(max_length=300, verbose_name='类别')),
                ('ucount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='数量')),
                ('uamt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总额')),
                ('zbsamt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='总校打款')),
                ('splace', models.CharField(blank=True, max_length=300, null=True, verbose_name='营销')),
                ('snote', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('fprestored', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='分校预存')),
                ('channel', models.CharField(blank=True, max_length=900, null=True, verbose_name='报名途径')),
                ('devf1', models.CharField(blank=True, max_length=300, null=True)),
                ('devf2', models.CharField(blank=True, max_length=300, null=True)),
                ('devf3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devf4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devf5', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300, verbose_name='学员id')),
                ('uname', models.CharField(max_length=300, verbose_name='学员姓名')),
                ('jexam', models.CharField(max_length=50, verbose_name='技能成绩')),
                ('bexam', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='笔试成绩')),
                ('devf1', models.CharField(blank=True, max_length=300, null=True)),
                ('devf2', models.CharField(blank=True, max_length=300, null=True)),
                ('devf3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ztype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ztype', models.CharField(max_length=300, verbose_name='类别')),
                ('devf1', models.CharField(blank=True, max_length=300, null=True)),
                ('devf2', models.CharField(blank=True, max_length=300, null=True)),
                ('devf3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
