# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0002_auto_20171018_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='qa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='问题')),
                ('opr_1', models.TextField(blank=True, null=True, verbose_name='选项1')),
                ('opr_2', models.TextField(blank=True, null=True, verbose_name='选项2')),
                ('opr_3', models.TextField(blank=True, null=True, verbose_name='选项3')),
                ('opr_4', models.TextField(blank=True, null=True, verbose_name='选项4')),
                ('opr_5', models.TextField(blank=True, null=True, verbose_name='选项5')),
                ('opr_6', models.TextField(blank=True, null=True, verbose_name='选项6')),
                ('opr_7', models.TextField(blank=True, null=True, verbose_name='选项7')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='解析')),
                ('beizhu', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('devf1', models.TextField(blank=True, null=True, verbose_name='自定义项1')),
                ('devf2', models.TextField(blank=True, null=True, verbose_name='自定义项2')),
                ('devf3', models.TextField(blank=True, null=True, verbose_name='自定义项3')),
            ],
        ),
        migrations.DeleteModel(
            name='express',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='ztype',
        ),
    ]
