# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0003_auto_20171024_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='答案'),
        ),
    ]
