# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0004_qa_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opr_1', models.CharField(blank=True, max_length=300, null=True)),
                ('imp_1', models.ImageField(height_field='url_height', upload_to='icons', width_field='url_width')),
                ('ty_1', models.CharField(blank=True, max_length=300, null=True)),
                ('beizhu', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('devf1', models.CharField(blank=True, max_length=300, null=True)),
                ('devf2', models.CharField(blank=True, max_length=300, null=True)),
                ('devf3', models.TextField(blank=True, null=True, verbose_name='自定义项3')),
            ],
        ),
    ]
